### ISSUE TITLE
System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by LStruz** [uuksu/RPGMakerDecrypter#24]
MGQPRPG 3\Data\Actors.rvdata2' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String , FileMode , FileAccess , FileShare , FileOptions )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.SyncWindowsFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream , String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , Boolean )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare )
   at System.IO.File.OpenWrite(String )
   at RPGMakerDecrypter.Decrypter.RGSSAD.ExtractFile(ArchivedFile archivedFile, String outputDirectoryPath, Boolean overrideExisting, Boolean createDirectory)
   at RPGMakerDecrypter.Decrypter.RGSSAD.ExtractAllFiles(String outputDirectoryPath, Boolean overrideExisting)
   at RPGMakerDecrypter.Cli.Program.Main(String[] args)

**Comment by LStruz** [comment]
could you please tell me how i could fix my problem with this issue, thanks in advance man

**Comment by uuksu** [comment]
Hey, sorry for taking so long to answer. Have you got this working? To me it seems some kind of permission issus, does the RPG Maker project exist in some directory where the Decrypter has no access?
